{% set name = "manif-split" %}
{% set version = "0.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/artivis/manif/archive/{{ version }}.tar.gz
    sha256: 739731e1eb83194c4977fa946ee63ba1aa8aadf757d67f3b183f2dfab64eff81
    patches:
      - 236.patch
      - 233.patch  # [win]

build:
  number: 7

outputs:
  - name: manif
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                               # [not win]
        - cmake
      host:
        - eigen
        - tl-optional
        - gtest
        - gmock
      run:
        - eigen
        - tl-optional
    test:
      commands:
        - test -f ${PREFIX}/include/manif/manif.h  # [not win]
        - test -f ${PREFIX}/share/manif/cmake/manifConfig.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\manif\\manif.h exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\manif\\cmake\\manifConfig.cmake exit 1  # [win] 

  - name: manifpy
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                               # [not win]
        - cmake
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - clang  # [win]
      host:
        - eigen
        - tl-optional
        - python
        - pip
        - numpy
        - pybind11
        - pybind11-abi
      run:
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - manifpy

about:
  home: https://github.com/artivis/manif
  license: MIT
  license_file: LICENSE
  summary: A small C++11 header-only library (with Python bindings) for Lie theory.

extra:
  recipe-maintainers:
    - traversaro
