azure:
  settings_win:
    pool:
      vmImage: windows-2019
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
